# Generated by Django 4.2.3 on 2024-03-06 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perguntas', '0002_resposta'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='perguntas/'),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='texto_adicional',
            field=models.TextField(blank=True, null=True),
        ),
    ]
